name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |        
        #docker login -u $DOCKER_USER --password-stdin DOCKER_PASSWORD
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build Docker Image
      run: |
        docker build -t gregoryreyesp/docker-graphql:1.0.1 .
        docker build -t gregoryreyesp/docker-graphql:latest .
    - name: push Docker Image
      run: |
        docker push gregoryreyesp/docker-graphql:1.0.1
        docker push gregoryreyesp/docker-graphql:latest

        
   
