name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version  
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |      
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        echo "New version: $NEW_VERSION!!!!!!!!"
        
    # - name: Build Docker Image
    #   run: |
    #     docker build -t gregoryreyesp/docker-graphql:1.0.1 .
    #     docker build -t gregoryreyesp/docker-graphql:latest .
    # - name: push Docker Image
    #   run: |
    #     docker push gregoryreyesp/docker-graphql:1.0.1
    #     docker push gregoryreyesp/docker-graphql:latest

        
   
